### Create a new TODO
POST http://localhost:8080/todos
Content-Type: application/json

{
  "name": "Novo",
  "description": "Desc Todo Novo",
  "priority": 2
}


### Get all TODO
GET http://localhost:8080/todos
#Accept: application/json


### Update a TODO
PUT http://localhost:8080/todos/2
Content-Type: application/json

{
  "id": 2,
  "name": "teste ricardo",
  "description": "update",
  "priority": 1
}


### DELETE TODO
DELETE http://localhost:8080/todos/1
